#!/bin/bash
# Helper script to switch to ChopperTracker account credentials
# This will help you run the ECR permissions script

echo "🔄 Switching to ChopperTracker account credentials..."
echo ""
echo "You have several options:"
echo ""
echo "Option 1: Use AWS Profile"
echo "  If you have a profile configured:"
echo "  export AWS_PROFILE=choppertracker"
echo "  aws sts get-caller-identity  # Should show account 038342322731"
echo ""
echo "Option 2: Export Credentials"
echo "  export AWS_ACCESS_KEY_ID='your-choppertracker-access-key'"
echo "  export AWS_SECRET_ACCESS_KEY='your-choppertracker-secret-key'"
echo "  unset AWS_PROFILE"
echo ""
echo "Option 3: Use aws configure"
echo "  aws configure --profile choppertracker"
echo "  # Enter ChopperTracker credentials when prompted"
echo "  export AWS_PROFILE=choppertracker"
echo ""
echo "After setting credentials, verify with:"
echo "  aws sts get-caller-identity"
echo "  # Should show Account: 038342322731"
echo ""
echo "Then run:"
echo "  ./scripts/grant-ecr-permissions.sh"