name: Deploy ChopperTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 038342322731

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install frontend dependencies
      working-directory: ./FrontEnd
      run: npm ci

    - name: Build frontend
      working-directory: ./FrontEnd
      run: npm run build

    - name: Deploy frontend to S3
      run: |
        # Create S3 bucket if it doesn't exist
        aws s3api head-bucket --bucket choppertracker-web-ui 2>/dev/null || \
        aws s3api create-bucket --bucket choppertracker-web-ui --region ${{ env.AWS_REGION }}
        
        # Disable block public access settings
        aws s3api put-public-access-block \
          --bucket choppertracker-web-ui \
          --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
        
        # Enable ACLs on the bucket (required for public access)
        aws s3api put-bucket-ownership-controls \
          --bucket choppertracker-web-ui \
          --ownership-controls Rules=[{ObjectOwnership=BucketOwnerPreferred}]
        
        # Enable static website hosting
        aws s3 website s3://choppertracker-web-ui \
          --index-document index.html \
          --error-document error.html
        
        # Upload files with public-read ACL
        aws s3 sync ./FrontEnd/dist s3://choppertracker-web-ui \
          --delete \
          --acl public-read \
          --cache-control "public, max-age=3600"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install backend dependencies
      run: |
        cd BackEnd
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy backend Lambda functions
      run: |
        cd BackEnd
        # Package Lambda functions
        zip -r lambda-deployment.zip . -x "*.git*" -x "*__pycache__*" -x "*.pyc"
        
        # Create Lambda functions (create first, then update if exists)
        # Function 1: choppertracker-start
        if aws lambda get-function --function-name choppertracker-start >/dev/null 2>&1; then
          echo "Function choppertracker-start exists, updating..."
          aws lambda update-function-code \
            --function-name choppertracker-start \
            --zip-file fileb://lambda-deployment.zip
        else
          echo "Creating function choppertracker-start..."
          aws lambda create-function \
            --function-name choppertracker-start \
            --runtime python3.11 \
            --role arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/lambda-execution-role \
            --handler src.main.start_handler \
            --zip-file fileb://lambda-deployment.zip \
            --timeout 30 \
            --memory-size 128
        fi
        
        # Function 2: choppertracker-stop  
        if aws lambda get-function --function-name choppertracker-stop >/dev/null 2>&1; then
          echo "Function choppertracker-stop exists, updating..."
          aws lambda update-function-code \
            --function-name choppertracker-stop \
            --zip-file fileb://lambda-deployment.zip
        else
          echo "Creating function choppertracker-stop..."
          aws lambda create-function \
            --function-name choppertracker-stop \
            --runtime python3.11 \
            --role arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/lambda-execution-role \
            --handler src.main.stop_handler \
            --zip-file fileb://lambda-deployment.zip \
            --timeout 30 \
            --memory-size 128
        fi

    - name: Update CloudFront distribution
      run: |
        # Get CloudFront distribution ID if exists
        DISTRIBUTION_ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?Comment=='ChopperTracker'].Id" \
          --output text)
        
        if [ ! -z "$DISTRIBUTION_ID" ]; then
          echo "Creating CloudFront invalidation for distribution $DISTRIBUTION_ID"
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
        else
          echo "No CloudFront distribution found"
        fi

    - name: Output deployment URL
      run: |
        echo "Frontend deployed to: http://choppertracker-web-ui.s3-website-${{ env.AWS_REGION }}.amazonaws.com"
        echo "Note: CloudFront distribution will be created separately if needed"